kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: jonaheinrichs
    password:
      from_secret: docker_hub_token
    repo: jonaheinrichs/yosys
    auto_tag: true
